### ISSUE TITLE
Wrong L1 inductance?

### ISSUE THREAD

**Issue by T94T** [sparkfun/Buck_Regulator_AP63203#1]
Shouldn't _L1_ be 3.9μH as mentioned in the datasheet? 4.7μH seems to be for the _AP63205_.

**Comment by adamgarbo** [comment]
@T94T seems so.
<img width="711" alt="image" src="https://user-images.githubusercontent.com/22924092/217405509-fb3d7729-d392-4267-9d02-5d26b8ef72b9.png">

**Comment by T94T** [comment]
Ok, we replaced the inductor with a 3.9μH one.

**Comment by adamgarbo** [comment]
You could have left the issue open for SparkFun to address.

Did you notice any significant difference in the output after changing the inductor?

**Comment by T94T** [comment]
There was no noticeable difference, but we didn't make any more precise measurements either.

**Comment by brhoff720** [comment]
Were you seeing any issues?  Using a slightly larger inductor shouldn't be an issue and according to the datasheet may improve efficiencies at lighter loads.

**Comment by T94T** [comment]
3.9μH is the value we go for.
